#!/bin/bash

# Turns on/off the display much quicker.

SLEEP_HOOK_FILE="/etc/pm/sleep.d/10-display-off"

case "$1" in
    start)
        # Inject sleep.d hook file.
        cp /userdata/system/custom/10-display-off "$SLEEP_HOOK_FILE"
        chmod +x "$SLEEP_HOOK_FILE"
        ;;
    stop)
        # Remove sleep.d hook file.
        rm "$SLEEP_HOOK_FILE"
        ;;
    *)
        # Code in here will be executed in all other conditions.
        echo "Usage: $0 {start|stop}"
        ;;
esac

exit $?