#!/bin/bash

# Persists the display temperature on reboot.

case "$1" in
    start)
        TEMPERATURE="$(batocera-settings-get display.temperature)"
        if [[ -n "$TEMPERATURE" ]]; then
            echo "$TEMPERATURE" > "/sys/devices/virtual/disp/disp/attr/color_temperature"
        fi
        ;;
    stop)
        TEMPERATURE="$(< /sys/devices/virtual/disp/disp/attr/color_temperature)"
        batocera-settings-set display.temperature "$TEMPERATURE"
        ;;
    *)
        # Code in here will be executed in all other conditions.
        echo "Usage: $0 {start|stop}"
        ;;
esac

exit $?