#!/bin/bash

# Reverts the commit that messes up external USB controller bindings.

BUSYBOX="/userdata/system/custom/busybox"
CONTROLLER_PY="/usr/lib/python3.12/site-packages/configgen/controller.py"
PATCH_FILE="/userdata/system/custom/revert-ext-controller-commit.patch"

case "$1" in
    start)
        # Backup controller.py for later.
        cp "$CONTROLLER_PY" "$CONTROLLER_PY.bk"

        # Patch controller.py.
        "$BUSYBOX" patch "$CONTROLLER_PY" "$PATCH_FILE"
        ;;
    stop)
        # Restore controller.py.bk.
        mv "$CONTROLLER_PY.bk" "$CONTROLLER_PY"
        ;;
    *)
        # Code in here will be executed in all other conditions.
        echo "Usage: $0 {start|stop}"
        ;;
esac

exit $?
